import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans premium-bg">
        <Header />
        <main className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-6 ">
          {children}
        </main>
      </body>
    </html>
  );
}